server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    diver-class-name: org.mariadb.jdbc.Driver
    # 아래 ${}부분은 pod를 실행하는 시점에 k8s의 secret자원을 활용
    url: jdbc:mariadb://${DB_HOST}:3306/ordersystem
    username: admin
    password: ${DB_PW}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  redis:
    host: redis-service
    port: 6379

cloud:
  aws:
    credentials:
      access-key: xx
      secret-key: yy
    region:
      static: ap-northeast-2
    s3:
      bucket: ordering-bucket-1

jwt:
  expirationAt: 1000
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 10000
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
